version: '3.8'

services:
  frontend:
    build: ./frontend
    ports: ["3000:3000"]
    depends_on:
      - backend
    environment:
      - REACT_APP_BASE_URL=http://3.222.246.46:8000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - mern_network
    restart: always

  backend:
    build: ./backend
    ports: ["8000:8000"]
    depends_on:
      mongo:
        condition: service_healthy
    environment:
      - MONGO_URI=mongodb://appuser:apppassword@mongo:27017/mern_stack?authSource=admin
      - ORIGIN=http://3.222.246.46:3000
    volumes:
      - ./backend:/app
    networks:
      - mern_network
    restart: always

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
      MONGO_INITDB_DATABASE: admin
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - mern_network
    healthcheck:
      test: |
        mongosh --eval "db.adminCommand('ping')" -u root -p rootpassword --authenticationDatabase admin --quiet
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 30s

networks:
  mern_network:
    driver: bridge

volumes:
  mongo_data: