name: 🚀 One-Step Deploy & Push

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy & Push Images
    runs-on: ubuntu-latest

    steps:
      - name: SSH and Deploy
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /home/ubuntu/your-project-name
            git pull origin main
            docker compose down
            docker compose up -d --build
            echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin
            docker tag frontend:latest ${{ secrets.DOCKER_HUB_USERNAME }}/frontend:latest
            docker tag backend:latest ${{ secrets.DOCKER_HUB_USERNAME }}/backend:latest
            docker push ${{ secrets.DOCKER_HUB_USERNAME }}/frontend:latest
            docker push ${{ secrets.DOCKER_HUB_USERNAME }}/backend:latest

            # Seed the backend
            backend_container=$(docker ps -qf "name=backend")
            docker exec $backend_container npm run seed
#add commit1